# Generated by Django 4.0.6 on 2022-07-13 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_evet_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cash',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='img',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='loc',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='sheet',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='body',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
