# Generated by Django 4.0.6 on 2022-07-14 13:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_event_cash_event_date_event_img_event_loc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='schedule',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
