# Generated by Django 4.0.6 on 2022-07-15 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_event_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='owner',
            field=models.CharField(default='guest', max_length=20),
        ),
    ]
