# Generated by Django 4.0.6 on 2022-07-15 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_event_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
    ]
