# Generated by Django 4.0.6 on 2022-07-18 03:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0006_remove_event_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall_id', models.IntegerField()),
                ('hall_name', models.CharField(max_length=40)),
                ('number_of_seats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_no', models.PositiveSmallIntegerField(unique=True)),
                ('row_no', models.PositiveSmallIntegerField()),
                ('seat_name', models.CharField(max_length=9, unique=True)),
                ('seat_status', models.CharField(choices=[('CANCELED', 'Canceled'), ('CONFIRMED', 'Confirmed'), ('BOOKED', 'Booked')], default='Confirmed', max_length=20)),
                ('number_of_seats', models.IntegerField()),
                ('booked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('event', models.ManyToManyField(to='base.event')),
            ],
        ),
    ]
