# Generated by Django 4.0.6 on 2022-07-18 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_hall_seat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='seat_name',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_no',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
